### ISSUE TITLE
Religion tooltip mentions vanilla religions

### ISSUE THREAD

**Issue by robmart** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#303] opened 2021-04-10 22:26 UTC
**Your mod version is:** d6c896e

**What expansions do you have installed?** Northern Lords

**Are you using any submods/mods? If so, which?** None

**Please explain your issue in as much detail as possible:** The religion tooltip mentions vanilla religious groups: Abrahamic, Eastern, Pagan

**Steps to reproduce the issue:** Open the religion tooltip by opening tooltips in this order: Any Faith (for example holy light) -> Faith -> Religion

**Upload an attachment below: .zip of your save, or screenshots:**
![bild](https://user-images.githubusercontent.com/4825809/114286153-812fe300-9a5c-11eb-9ab5-f694deb9f397.png)

**Comment by MemeWizard** [comment] 2021-04-10 22:28
Duplicate of #101

**Closed by MemeWizard** 2021-04-10 22:28 UTC
Labels: :page_facing_up: localisation :pen:

**Comment by robmart** [comment] 2021-04-10 22:38
> 
> 
> Duplicate of #101

My bad, sorry.
